### ISSUE TITLE
Ładny mail do potwierdzenia założonego konta.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/sungate#20]
### Trzeba stworzyć plik HTML zawierający coś więcej niż tylko link aktywacyjny. Link ten powinien być schowany pod jakimś przyciskiem, a wszystko dookoła jakoś wyglądać. 
Poniże podsyłam kilka przykładów, jednak trzeba design dostosować do naszej strony:
[1](http://reallygoodemails.com/wp-content/uploads/2015/01/Please-Confirm-Your-Email_Mobile.png) [2](http://reallygoodemails.com/wp-content/uploads/2015/07/Confirm-your-Twitter-account_Mobile.png) [3](https://support.shazam.com/hc/en-us/article_attachments/202035067/Screen_Shot_2015-06-11_at_11.42.52.png)

Pomyślałem, że można byłoby przy okazji zrobić jakiś stan rejestracji. W sumie to przydałby się stan wszystkiego, tak jak w poniżej dla rejestracji:
[link](https://customercare.23andme.com/hc/en-us/article_attachments/212715868/Verify_your_email.png)

#### Tasks:
- [x] Generating current position ( @arbuz93 )
- [ ] Create design for email with activation link ( @Drego31 )
- [x] Include html to mail which will be sent.

**Comment by arbuz93** [comment]
Zajmę się generowaniem stanu - gdzie aktualnie się znajdujemy.

**Comment by dbetka** [comment]
Tutaj jest wstępnie zrobiony wygląd.
[main.txt](https://github.com/arbuz-team/sungate/files/666608/main.txt) // wystarczy zamienić txt na html

**Comment by dbetka** [comment]
Stan tak jak wspominałem, można za pomocą cookies zrobić. @arbuz93

**Comment by dbetka** [comment]
Już praktycznie skończony - tylko do poprawek.
[main.txt](https://github.com/arbuz-team/sungate/files/666648/main.txt)

**Comment by arbuz93** [comment]
Send complex email: [link](https://www.vlent.nl/weblog/2014/01/15/sending-emails-with-embedded-images-in-django/)
Temporary address URL to send mail: /root/login/

**Comment by arbuz93** [comment]
Send email with image: https://github.com/arbuz-team/sungate/commit/c118740cf0c24cef3ec1352502a23b1f10b68b8d
Your turn @Drego31. You have to improve CSS.

**Comment by dbetka** [comment]
@arbuz93 
https://github.com/arbuz-team/sungate/commit/7e60c2816a6dbac9816024e03b8fe6e4c43d12c6
